Repository dotnet/cli, pull requests merged in 2018-06, with the labels that each got.

#9380 Upgrade to aspnetcore 2.1.1-rtm-30818 and react to file name change
  build/BundledDotnetTools.props
  build/BundledRuntimes.props
  build/DependencyVersions.props
  build/NugetConfigFile.targets
  src/dotnet/dotnet.csproj
  test/Microsoft.DotNet.Cli.Utils.Tests/Microsoft.DotNet.Cli.Utils.Tests.csproj
Labels: Approved to merge, servicing-approved

#9394 Revert "Fix MSBuild invocation to quote property option values."
  TestAssets/TestProjects/ProjectPrintsNoWarn/ProjectPrintsNoWarn.csproj
  src/Microsoft.DotNet.Cli.Utils/ArgumentEscaper.cs
  src/Microsoft.DotNet.Cli.Utils/MSBuildForwardingAppWithoutLogging.cs
  src/dotnet/commands/dotnet-test/Program.cs
  test/dotnet-msbuild.Tests/GivenDotnetBuildInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetCleanInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetMSBuildBuildsProjects.cs
  test/dotnet-msbuild.Tests/GivenDotnetPackInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetPublishInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetRestoreInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetStoreInvocation.cs
Labels: Approved to merge

#9402 Port 2.1.3xx add retry when directory.move
  src/Microsoft.DotNet.Cli.Utils/FileAccessRetryer.cs
  src/dotnet/ShellShim/ShellShimRepository.cs
  src/dotnet/ToolPackage/ToolPackageInstaller.cs
  src/dotnet/ToolPackage/ToolPackageInstance.cs
Labels: servicing-consideration

#9374 Set Default aspnetcore metapackage versions
  build/MSBuildExtensions.targets
Labels: servicing-approved

#9365 Add dotnet-tool manpages and update others
  Documentation/manpages/sdk/dotnet-add-package.1
  Documentation/manpages/sdk/dotnet-add-reference.1
  Documentation/manpages/sdk/dotnet-build-server.1
  Documentation/manpages/sdk/dotnet-build.1
  Documentation/manpages/sdk/dotnet-clean.1
  Documentation/manpages/sdk/dotnet-help.1
  Documentation/manpages/sdk/dotnet-install-script.1
  Documentation/manpages/sdk/dotnet-list-reference.1
  Documentation/manpages/sdk/dotnet-migrate.1
  Documentation/manpages/sdk/dotnet-msbuild.1
  Documentation/manpages/sdk/dotnet-new.1
  Documentation/manpages/sdk/dotnet-nuget-delete.1
  Documentation/manpages/sdk/dotnet-nuget-locals.1
  Documentation/manpages/sdk/dotnet-nuget-push.1
  Documentation/manpages/sdk/dotnet-pack.1
  Documentation/manpages/sdk/dotnet-publish.1
  Documentation/manpages/sdk/dotnet-remove-package.1
  Documentation/manpages/sdk/dotnet-remove-reference.1
  Documentation/manpages/sdk/dotnet-restore.1
  Documentation/manpages/sdk/dotnet-run.1
  Documentation/manpages/sdk/dotnet-sln.1
  Documentation/manpages/sdk/dotnet-store.1
  Documentation/manpages/sdk/dotnet-test.1
  Documentation/manpages/sdk/dotnet-tool-install.1
  Documentation/manpages/sdk/dotnet-tool-list.1
  Documentation/manpages/sdk/dotnet-tool-uninstall.1
  Documentation/manpages/sdk/dotnet-tool-update.1
  Documentation/manpages/sdk/dotnet-vstest.1
  Documentation/manpages/sdk/dotnet.1
Labels: Approved to merge, community

#9416 Fix alpine file ownership issues with newer docker
  scripts/docker/alpine.3.6/Dockerfile
Labels: infrastructure

#9382 Update runtimeconfig.json doc for 2.1
  Documentation/specs/runtime-configuration-file.md
Labels: documentation

#9415 Insert NuGet Build 4.8.0-preview3.5244 into cli
  build/DependencyVersions.props
Labels: Approved to merge

#9371 Simplified combining dictionaries in Telemetry
  src/dotnet/Telemetry/Telemetry.cs
Labels: community

#9421 Pass "PB_AssetRootUrl" explictly on the MSBuild call and fix two tests
  build/DependencyVersions.props
  build/Test.targets
  test/Microsoft.DotNet.Cli.Utils.Tests/GivenAProjectToolsCommandResolver.cs
  test/dotnet-new.Tests/GivenThatIWantANewApp.cs
Labels: infrastructure

#9418 Remove obsolete manpages
  Documentation/manpages/sdk/dotnet-compile-native.1
  Documentation/manpages/sdk/dotnet-compile.1
Labels: Approved to merge, community

#9360 Update Sha256Hasher.cs
  src/dotnet/Telemetry/Sha256Hasher.cs
Labels: community

#9424 Testplatform 15.8.0-preview-20180605-02
  build/DependencyVersions.props
Labels: Approved to merge

#9363 Always store absolute full path in directory and file path
  src/Microsoft.DotNet.InternalAbstractions/DirectoryPath.cs
  src/Microsoft.DotNet.InternalAbstractions/FilePath.cs
  test/Microsoft.DotNet.Tools.Tests.Utilities/Mock/FileSystemMockBuilder.cs
  test/dotnet.Tests/BuildServerTests/BuildServerProviderTests.cs
  test/dotnet.Tests/BuildServerTests/RazorServerTests.cs
  test/dotnet.Tests/CommandTests/ToolInstallCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolUninstallCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolUpdateCommandTests.cs
Labels: Approved to merge

#9430 Drop the LZMA archive for every build
  build/Publish.targets
  build/compile/LzmaArchive.targets
Labels: infrastructure

#9436 MSBuild 15.8.86
  build/DependencyVersions.props
Labels: Approved to merge

#9446 Updating the CLI stage0 to 2.1.300 and fixing some build failures.
  build/BundledDotnetTools.proj
  run-build.ps1
  run-build.sh
  test/InsertionTests/InsertionTests.csproj
  test/Microsoft.DotNet.Cli.Utils.Tests/Microsoft.DotNet.Cli.Utils.Tests.csproj
Labels: Area-Infrastructure

#9470 Correcting the 'Channel' and 'BranchName' to "release/2.1.3xx"
  build/BranchInfo.props
Labels: infrastructure

#9483 Update current install scripts from CLI rel/1.1.0
  scripts/obtain/dotnet-install.sh
Labels: infrastructure

#9495 Add global NoWarn for: 'NU5104'
  build/BuildDefaults.props
Labels: infrastructure

#9491 Fix the 'Microsoft.AspNet.Core.Mvc' versioning
  TestAssets/TestProjects/TestRazorApp/TestRazorApp.csproj
  build/DependencyVersions.props
Labels: infrastructure

#9473 Update VS insertion package name
  build/package/Installer.MSI.targets
  packaging/windows/clisdk/VS.Redist.Common.Net.Core.SDK.x64.2.1.2xx.nuspec
  packaging/windows/clisdk/VS.Redist.Common.Net.Core.SDK.x86.2.1.2xx.nuspec
Labels: Area-Infrastructure

#9507 Test and automatic Update default package version
  build/MSBuildExtensions.targets
  build/Microsoft.DotNet.Cli.tasks
  build/NugetConfigFile.targets
  build_projects/dotnet-cli-build/GetUseBundledVersionAsDefaultVersion.cs
  test/EndToEnd/GivenFrameworkDependentApps.cs
  test/EndToEnd/GivenSelfContainedAppsRollForward.cs
  test/EndToEnd/SupportedNetCoreAppVersions.cs
Labels: Approved to merge

#9529 Align f# with dev15.8
  build/DependencyVersions.props
Labels: Approved to merge

#9496 Update templates to carry test SDK 15.8.0-preview-20180610-02
  build/DependencyVersions.props
  build/NugetConfigFile.targets
Labels: Approved to merge

#9502 Adding 'NoSuffix' legs to the CI
  build/BuildDefaults.props
  netci.groovy
  scripts/docker/opensuse.42.3/Dockerfile
Labels: infrastructure

#9525 Use correct nuget version normalized format
  src/dotnet/ToolPackage/ToolPackageInstaller.cs
  test/Microsoft.DotNet.ToolPackage.Tests/ToolPackageInstallerTests.cs
Labels: Approved to merge

#9535 Fix the CI legs; CLI:release/2.1.3xx
  netci.groovy
Labels: infrastructure

#9509 Pass BaseIntermediateOutputPath via xml
  src/dotnet/ToolPackage/IProjectRestorer.cs
  src/dotnet/ToolPackage/ToolPackageInstaller.cs
  src/dotnet/commands/dotnet-tool/install/ProjectRestorer.cs
  test/Microsoft.DotNet.ToolPackage.Tests/ToolPackageInstallerTests.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ProjectRestorerMock.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageInstallerMock.cs
Labels: Approved to merge

#9546 Use blob feed instead of myget
  build/NugetConfigFile.targets
  test/Microsoft.DotNet.TestFramework/TestAssetInstance.cs
Labels: infrastructure

#9543 MSBuild 15.8.125
  build/DependencyVersions.props
Labels: Approved to merge

#9555 Add nunit project and item templates to bundle
  build/BundledTemplates.props
  build/DependencyVersions.props
  test/dotnet-new.Tests/GivenThatIWantANewAppWithSpecifiedType.cs
Labels: Approved to merge

#9567 Updating branding to 401.
  build/BranchInfo.props
  build/Version.props
Labels: Approved to merge

#9568 Update SDK to 2.1.400-preview-63027-01
  build/DependencyVersions.props
Labels: Approved to merge

#9467 Add a restore and add pkg commands interactive flag
  src/dotnet/commands/dotnet-add/dotnet-add-package/AddPackageParser.cs
  src/dotnet/commands/dotnet-add/dotnet-add-package/LocalizableStrings.resx
  src/dotnet/commands/dotnet-add/dotnet-add-package/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-add/dotnet-add-package/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-add/dotnet-add-package/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-add/dotnet-add-package/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-add/dotnet-add-package/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-add/dotnet-add-package/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-add/dotnet-add-package/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-add/dotnet-add-package/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-add/dotnet-add-package/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-add/dotnet-add-package/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-add/dotnet-add-package/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-add/dotnet-add-package/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-add/dotnet-add-package/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/commands/dotnet-nuget/Program.cs
  src/dotnet/commands/dotnet-restore/LocalizableStrings.resx
  src/dotnet/commands/dotnet-restore/RestoreCommandParser.cs
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Approved to merge

#9588 Update the 'Microsoft.DotNet.Archive' version.
  build/DependencyVersions.props
Labels: infrastructure
