Repository dotnet/cli, pull requests merged in 2018-03, with the labels that each got.

#8712 Creating and publishing 'symbols.nuget' to the blob feed.
  build/AzureInfo.props
  build/Branding.props
  build/NugetConfigFile.targets
  build/Package.targets
  build/Publish.targets
  build/package/Installer.MSI.targets
  build/package/Layout.targets
  build/package/Nupkg.targets
  build/package/Symbols.csproj
  build/package/Symbols.targets
  build/publish/PublishNupkgToBlobFeed.targets
  build_projects/dotnet-cli-build/DotNetPack.cs
  scripts/dockerrun.sh
  src/Microsoft.DotNet.InternalAbstractions/Microsoft.DotNet.InternalAbstractions.csproj
  src/redist/redist.csproj
Labels: build, infrastructure

#8630 Branding changes for TestPlatform 15.6 RTM
  build/DependencyVersions.props
Labels: approved to merge

#8693 Update to the 15.6 RTM version of the test SDK in templates
  build/DependencyVersions.props
Labels: approved to merge

#8791 Enable 'arm' builds in the CLI
  README.md
  build/BackwardsCompatibilityRuntimes.props
  build/BuildDefaults.props
  build/BuildInfo.targets
  build/BundledRuntimes.props
  build/Package.targets
  build/Publish.targets
  build/Test.targets
  build/publish/Badge.targets
  build/publish/RuntimeCoherence.targets
  build_projects/dotnet-cli-build/CheckIfAllBuildsHavePublished.cs
  netci.groovy
  run-build.ps1
  run-build.sh
  src/redist/redist.csproj
Labels: build, infrastructure

#8797 Follow-up PR for Linux-arm; CLI:master
  build/BuildDefaults.props
  build/publish/Badge.targets
  netci.groovy
Labels: build, infrastructure

#8821 Alpine fix; plus 1
  scripts/obtain/dotnet-install.sh
Labels: infrastructure

#8809 Better using facing string
  src/dotnet/CommonLocalizableStrings.resx
  src/dotnet/commands/dotnet-install/dotnet-install-tool/LocalizableStrings.resx
  src/dotnet/commands/dotnet-install/dotnet-install-tool/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-install/dotnet-install-tool/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-install/dotnet-install-tool/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-install/dotnet-install-tool/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-install/dotnet-install-tool/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-install/dotnet-install-tool/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-install/dotnet-install-tool/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-install/dotnet-install-tool/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-install/dotnet-install-tool/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-install/dotnet-install-tool/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-install/dotnet-install-tool/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-install/dotnet-install-tool/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-install/dotnet-install-tool/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/commands/dotnet-uninstall/tool/LocalizableStrings.resx
  src/dotnet/commands/dotnet-uninstall/tool/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-uninstall/tool/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-uninstall/tool/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-uninstall/tool/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-uninstall/tool/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-uninstall/tool/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-uninstall/tool/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-uninstall/tool/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-uninstall/tool/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-uninstall/tool/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-uninstall/tool/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-uninstall/tool/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-uninstall/tool/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
Labels: tool

#8853 Updating NuGet to 4.6.1-rtm-5019
  build/Branding.props
  build/DependencyVersions.props
  build/NugetConfigFile.targets
  build/Version.props
  packaging/osx/clisdk/resources/cs.lproj/conclusion.html
  packaging/osx/clisdk/resources/de.lproj/conclusion.html
  packaging/osx/clisdk/resources/en.lproj/conclusion.html
  packaging/osx/clisdk/resources/es.lproj/conclusion.html
  packaging/osx/clisdk/resources/fr.lproj/conclusion.html
  packaging/osx/clisdk/resources/it.lproj/conclusion.html
  packaging/osx/clisdk/resources/ja.lproj/conclusion.html
  packaging/osx/clisdk/resources/ko.lproj/conclusion.html
  packaging/osx/clisdk/resources/pl.lproj/conclusion.html
  packaging/osx/clisdk/resources/pt-br.lproj/conclusion.html
  packaging/osx/clisdk/resources/ru.lproj/conclusion.html
  packaging/osx/clisdk/resources/tr.lproj/conclusion.html
  packaging/osx/clisdk/resources/zh-hans.lproj/conclusion.html
  packaging/osx/clisdk/resources/zh-hant.lproj/conclusion.html
  packaging/windows/clisdk/bundle.wxl
Labels: approved to merge

#8866 TestPlatform 15.7 preview 3 insertion
  build/DependencyVersions.props
Labels: approved to merge
