Repository dotnet/cli, pull requests merged in 2018-04, with the labels that each got.

#8962 Fix prodcon
  build/DependencyVersions.props
  testAsset.props
Labels: infrastructure

#9031 Fixing build-break in AllLinuxDistrosNativeInstallers; CLI:master
  build/package/Installer.RPM.targets
Labels: build

#9049 Terminate the 'StartsWith' string in the badge existence check.
  build/publish/FinishBuild.targets
  build_projects/dotnet-cli-build/CheckIfAllBuildsHavePublished.cs
Labels: build

#9086 Sign the 'nupkg' files; CLI:release/2.1.3xx
  build/Signing.proj
Labels: infrastructure

#9081 Update dotnet manpages for Unix
  Documentation/manpages/sdk/dotnet-new.1
  Documentation/manpages/tool/README.md
  Documentation/manpages/tool/update-man-pages.sh
Labels: approved to merge

#9090 pick up nuget loc
  src/redist/redist.csproj
Labels: approved to merge

#9089 Rename buildserver command.
  src/dotnet/BuiltInCommandsCatalog.cs
  src/dotnet/commands/dotnet-buildserver/BuildServerCommand.cs
  src/dotnet/commands/dotnet-buildserver/BuildServerCommandParser.cs
  src/dotnet/commands/dotnet-help/HelpUsageText.cs
  test/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
  test/dotnet.Tests/CommandTests/BuildServerShutdownCommandTests.cs
  test/dotnet.Tests/ParserTests/BuildServerShutdownParserTests.cs
Labels: approved to merge

#9019 Update test templates to use the 15.7.0 test SDK
  build/DependencyVersions.props
Labels: approved to merge

#9093 Update Roslyn to 2.8.0-dev-62817-01
  build/DependencyVersions.props
Labels: approved to merge

#9101 Updating CLI branding to RC1
  build/Version.props
Labels: approved to merge

#9096 Fix .deb and .rpm dependency on the aspnetcore-store package
  build/DependencyVersions.props
  build/package/Installer.DEB.targets
  build/package/Installer.RPM.targets
  test/EndToEnd/GivenDotNetLinuxInstallers.cs
Labels: approved to merge

#9099 Implement Razor server discovery by pid file.
  src/dotnet/BuildServer/BuildServerException.cs
  src/dotnet/BuildServer/BuildServerProvider.cs
  src/dotnet/BuildServer/IBuildServer.cs
  src/dotnet/BuildServer/IBuildServerManager.cs
  src/dotnet/BuildServer/IBuildServerProvider.cs
  src/dotnet/BuildServer/LocalizableStrings.resx
  src/dotnet/BuildServer/MSBuildServer.cs
  src/dotnet/BuildServer/MSBuildServerManager.cs
  src/dotnet/BuildServer/RazorAssemblyResolver.cs
  src/dotnet/BuildServer/RazorPidFile.cs
  src/dotnet/BuildServer/RazorServer.cs
  src/dotnet/BuildServer/RazorServerManager.cs
  src/dotnet/BuildServer/Result.cs
  src/dotnet/BuildServer/VBCSCompilerServer.cs
  src/dotnet/BuildServer/xlf/LocalizableStrings.cs.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.de.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.es.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.fr.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.it.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.ja.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.ko.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.pl.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.ru.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.tr.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/commands/dotnet-buildserver/shutdown/BuildServerShutdownCommand.cs
  src/dotnet/commands/dotnet-buildserver/shutdown/LocalizableStrings.resx
  src/dotnet/commands/dotnet-buildserver/shutdown/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-buildserver/shutdown/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-buildserver/shutdown/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-buildserver/shutdown/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-buildserver/shutdown/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-buildserver/shutdown/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-buildserver/shutdown/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-buildserver/shutdown/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-buildserver/shutdown/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-buildserver/shutdown/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-buildserver/shutdown/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-buildserver/shutdown/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-buildserver/shutdown/xlf/LocalizableStrings.zh-Hant.xlf
  test/Microsoft.DotNet.Tools.Tests.Utilities/Mock/FileSystemMockBuilder.cs
  test/dotnet.Tests/BuildServerTests/BuildServerProviderTests.cs
  test/dotnet.Tests/BuildServerTests/RazorServerManagerTests.cs
  test/dotnet.Tests/BuildServerTests/RazorServerTests.cs
  test/dotnet.Tests/BuildServerTests/VBCSCompilerServerManagerTests.cs
  test/dotnet.Tests/BuildServerTests/VBCSCompilerServerTests.cs
  test/dotnet.Tests/CommandTests/BuildServerShutdownCommandTests.cs
Labels: approved to merge

#9116 [release/2.1.3xx] Replace alpine with linux-musl builds
  README.md
  TestAssets/TestProjects/AppWithCorruptedLaunchSettings/AppWithCorruptedLaunchSettings.csproj
  TestAssets/TestProjects/AppWithLaunchSettings/AppWithLaunchSettings.csproj
  TestAssets/TestProjects/AppWithLaunchSettingsNoDefault/AppWithLaunchSettingsNoDefault.csproj
  TestAssets/TestProjects/MSBuildTestApp/MSBuildTestApp.csproj
  build/Branding.props
  build/BuildDefaults.props
  build/DependencyVersions.props
  build/DerivedHostMachineInfo.props
  build/NugetConfigFile.targets
  build/publish/Badge.targets
  build_projects/dotnet-cli-build/CheckIfAllBuildsHavePublished.cs
  netci.groovy
  scripts/obtain/dotnet-install.sh
  test/Microsoft.DotNet.MSBuildSdkResolver.Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests.csproj
  test/Microsoft.DotNet.Tools.Tests.Utilities/EnvironmentInfo.cs
Labels: approved to merge

#9115 Insert NuGet Build 4.7.0-rtm.5122 into cli
  build/DependencyVersions.props
Labels: approved to merge

#9117 Unblock build
  test/Microsoft.DotNet.ToolPackage.Tests/Microsoft.DotNet.ToolPackage.Tests.csproj
Labels: approved to merge

#9097 Add bundled aspnetcore runtime framework versions
  TestAssets/TestProjects/TestWebAppSimple/Program.cs
  TestAssets/TestProjects/TestWebAppSimple/Startup.cs
  TestAssets/TestProjects/TestWebAppSimple/TestWebAppSimple.csproj
  build/DependencyVersions.props
  build/MSBuildExtensions.targets
  test/EndToEnd/GivenAspNetAppsResolveImplicitVersions.cs
Labels: approved to merge

#9134 Update Roslyn to 2.8.0-beta4-62824-10
  build/DependencyVersions.props
Labels: approved to merge

#9130 Fix linux musl; CLI:release/2.1.3xx
  build/BundledRuntimes.props
  build/DependencyVersions.props
Labels: approved to merge, infrastructure

#9146 Explicitly note whether the package version props is being overridden
  build/DownloadPackageVersions.targets
Labels: Approved to merge, infrastructure

#9155 Update SDK to 2.1.200-preview-62826-08
  build/DependencyVersions.props
Labels: Approved to merge

#9153 Fix MSBuild invocation to quote property option values.
  TestAssets/TestProjects/ProjectPrintsNoWarn/ProjectPrintsNoWarn.csproj
  src/Microsoft.DotNet.Cli.Utils/ArgumentEscaper.cs
  src/Microsoft.DotNet.Cli.Utils/MSBuildForwardingAppWithoutLogging.cs
  src/dotnet/commands/dotnet-test/Program.cs
  test/dotnet-msbuild.Tests/GivenDotnetBuildInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetCleanInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetMSBuildBuildsProjects.cs
  test/dotnet-msbuild.Tests/GivenDotnetPackInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetPublishInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetRestoreInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetStoreInvocation.cs
Labels: Approved to merge

#9175 Update version to rtm
  build/Version.props
Labels: Approved to merge

#9150 Use cp -u on linux-musl
  README.md
  scripts/obtain/dotnet-install.sh
Labels: Approved to merge, infrastructure

#9137 Fix --source-feed option for tool install and update commands.
  src/dotnet/ToolPackage/ToolPackageInstaller.cs
  test/Microsoft.DotNet.ToolPackage.Tests/ToolPackageInstallerTests.cs
Labels: Approved to merge

#9163 Include aspnetcore in the linux-arm build,
  build/BundledRuntimes.props
Labels: Approved to merge

#9160 Fix Razor server shutdown on Windows.
  TestAssets/TestProjects/TestRazorApp/Areas/MyFeature/Pages/Page1.cshtml
  TestAssets/TestProjects/TestRazorApp/Areas/MyFeature/Pages/Page1.cshtml.cs
  TestAssets/TestProjects/TestRazorApp/TestRazorApp.csproj
  src/dotnet/BuildServer/BuildServerProvider.cs
  src/dotnet/BuildServer/LocalizableStrings.resx
  src/dotnet/BuildServer/RazorPidFile.cs
  src/dotnet/BuildServer/xlf/LocalizableStrings.cs.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.de.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.es.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.fr.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.it.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.ja.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.ko.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.pl.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.ru.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.tr.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/BuildServer/xlf/LocalizableStrings.zh-Hant.xlf
  test/Microsoft.DotNet.Tools.Tests.Utilities/Commands/BuildServerCommand.cs
  test/Microsoft.DotNet.Tools.Tests.Utilities/Mock/FileSystemMockBuilder.cs
  test/dotnet.Tests/BuildServerTests/BuildServerProviderTests.cs
  test/dotnet.Tests/CommandTests/BuildServerShutdownCommandTests.cs
Labels: Approved to merge

#9123 Mark both CLI NuPkgs as "NonShipping=true"
  build/Signing.proj
  build/publish/PublishNupkgToBlobFeed.targets
Labels: Approved to merge, infrastructure
