Repository dotnet/cli, pull requests merged in 2018-11, with the labels that each got.

#10246 NuGet prob nuget.config should start from the directory of the manifest file
  src/dotnet/ToolManifest/ToolManifestFinder.cs
  src/dotnet/ToolManifest/ToolManifestPackage.cs
  src/dotnet/commands/dotnet-tool/restore/ToolRestoreCommand.cs
  test/Microsoft.DotNet.ToolPackage.Tests/ToolPackageInstallerTests.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/MockFeedType.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ProjectRestorerMock.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageInstallerMock.cs
  test/Microsoft.DotNet.Tools.Tests.Utilities/NuGetConfig.cs
  test/dotnet.Tests/CommandTests/ToolManifestTests.cs
  test/dotnet.Tests/CommandTests/ToolRestoreCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolRestoreCommandWithMultipleNugetConfigTests.cs
  test/dotnet.Tests/CommandTests/ToolUpdateCommandTests.cs
Labels: tool

#10249 Dotnet tool restore in parallel
  scripts/cli-build-env.bat
  scripts/cli-build-env.sh
  src/dotnet/ToolPackage/RestoredCommand.cs
  src/dotnet/commands/dotnet-tool/restore/ToolRestoreCommand.cs
  test/Microsoft.DotNet.Tools.Tests.Utilities/Mock/FileSystemMockBuilder.cs
  test/dotnet.Tests/CommandTests/ToolRestoreCommandTests.cs
Labels: tool

#10303 Adding downloads of 'arm' and 'arm64'
  scripts/obtain/dotnet-install.ps1
Labels: Install-Script

#10299 Can add entry to tool manifest file
  src/dotnet/ToolManifest/LocalizableStrings.resx
  src/dotnet/ToolManifest/ToolManifestEditor.cs
  src/dotnet/ToolManifest/ToolManifestFinder.cs
  src/dotnet/ToolManifest/ToolManifestPackage.cs
  src/dotnet/ToolManifest/xlf/LocalizableStrings.cs.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.de.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.es.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.fr.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.it.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.ja.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.ko.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.pl.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.ru.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.tr.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet.Tests/CommandTests/ToolManifestEditorTests.cs
  test/dotnet.Tests/CommandTests/ToolManifestFinderTests.cs
  test/dotnet.Tests/CommandTests/ToolRestoreCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolRestoreCommandWithMultipleNugetConfigTests.cs
Labels: tool

#10321 Adding explicit dependencies to NuGet and NewtonSoft.Json to update-dependencies
  build_projects/update-dependencies/update-dependencies.csproj
Labels: Area-Infrastructure

#10349 Bump SDK package to 3.0.100-preview.18565.2.
  eng/Versions.props
Labels: Area-Infrastructure

#10350 Bump SDK package version to 3.0.100-preview.18565.3.
  eng/Versions.props
Labels: Area-Infrastructure

#10315 Dotnet tool uninstall local
  scripts/cli-test-env.bat
  scripts/cli-test-env.sh
  src/dotnet/ToolManifest/IToolManifestEditor.cs
  src/dotnet/ToolManifest/LocalizableStrings.resx
  src/dotnet/ToolManifest/ToolManifestEditor.cs
  src/dotnet/ToolManifest/xlf/LocalizableStrings.cs.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.de.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.es.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.fr.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.it.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.ja.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.ko.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.pl.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.ru.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.tr.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/commands/dotnet-tool/install/LocalizableStrings.resx
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/commands/dotnet-tool/uninstall/LocalizableStrings.resx
  src/dotnet/commands/dotnet-tool/uninstall/ToolUninstallCommand.cs
  src/dotnet/commands/dotnet-tool/uninstall/ToolUninstallCommandParser.cs
  src/dotnet/commands/dotnet-tool/uninstall/ToolUninstallGlobalOrToolPathCommand.cs
  src/dotnet/commands/dotnet-tool/uninstall/ToolUninstallLocalCommand.cs
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet.Tests/CommandTests/ToolManifestEditorTests.cs
  test/dotnet.Tests/CommandTests/ToolUninstallCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolUninstallGlobalOrToolPathCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolUninstallLocalCommandTests.cs
  test/dotnet.Tests/ParserTests/UninstallToolParserTests.cs
Labels: tool

#10366 Bump SDK package to `3.0.100-preview.18569.3`.
  eng/Versions.props
Labels: release blocking

#10373 Updating the release/2.2.2xx README
  README.md
Labels: infrastructure

#10370 update dotnet-new-nunit dependency version
  build/DependencyVersions.props
Labels: Servicing-approved

#10408 Bump SDK package to `3.0.100-preview.18578.2`.
  eng/Versions.props
Labels: release blocking

#10409 Fix build status badge to point at dnceng.
  README.md
Labels: Area-Infrastructure

#10407 Remove query NuGetGlobalPackagesFolder during command resolve
  src/dotnet/CommandFactory/CommandResolution/LocalToolsCommandResolver.cs
  src/dotnet/ToolPackage/ILocalToolsResolverCache.cs
  src/dotnet/ToolPackage/LocalToolsResolverCache.cs
  src/dotnet/commands/dotnet-tool/install/ToolInstallLocalCommand.cs
  src/dotnet/commands/dotnet-tool/restore/ToolRestoreCommand.cs
  test/Microsoft.DotNet.Cli.Utils.Tests/NuGetGlobalPackagesFolder.cs
  test/Microsoft.DotNet.CommandFactory.Tests/GivenALocalToolsCommandResolver.cs
  test/Microsoft.DotNet.ToolPackage.Tests/LocalToolsResolverCacheTests.cs
  test/Microsoft.DotNet.ToolPackage.Tests/ToolPackageInstallerNugetCacheTests.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageInstallerMock.cs
  test/Microsoft.DotNet.Tools.Tests.Utilities/NuGetGlobalPackagesFolder.cs
  test/dotnet.Tests/CommandTests/ToolInstallLocalCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolRestoreCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolRestoreCommandWithMultipleNugetConfigTests.cs
Labels: tool

#10374 Could not restore manifest file with markOfTheWeb
  src/Microsoft.DotNet.Cli.Utils/DangerousFileDetector.cs
  src/Microsoft.DotNet.Cli.Utils/IDangerousFileDetector.cs
  src/Microsoft.DotNet.Cli.Utils/Interop.cs
  src/dotnet/ToolManifest/LocalizableStrings.resx
  src/dotnet/ToolManifest/ToolManifestEditor.cs
  src/dotnet/ToolManifest/ToolManifestFinder.cs
  src/dotnet/ToolManifest/xlf/LocalizableStrings.cs.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.de.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.es.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.fr.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.it.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.ja.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.ko.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.pl.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.ru.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.tr.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.zh-Hant.xlf
  test/Microsoft.DotNet.Cli.Utils.Tests/DangerousFileDetectorTests.cs
  test/Microsoft.DotNet.CommandFactory.Tests/GivenALocalToolsCommandResolver.cs
  test/dotnet.Tests/CommandTests/FakeDangerousFileDetector.cs
  test/dotnet.Tests/CommandTests/ToolInstallLocalCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolManifestEditorTests.cs
  test/dotnet.Tests/CommandTests/ToolManifestFinderTests.cs
  test/dotnet.Tests/CommandTests/ToolRestoreCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolUninstallLocalCommandTests.cs
Labels: tool
