Repository dotnet/cli, pull requests merged in 2018-07, with the labels that each got.

#9604 Removing 'Locked-file' test; CLI:release/2.1.3xx
  README.md
  test/Microsoft.DotNet.Cli.Utils.Tests/GivenThatWeWantToReadLockFilesQuickly.cs
Labels: infrastructure

#9566 Log a verbose message when DOTNET_CLI_HOME is being used.
  src/Microsoft.DotNet.Cli.Utils/LocalizableStrings.resx
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.cs.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.de.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.es.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.fr.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.it.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.ja.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.ko.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.pl.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.pt-BR.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.ru.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.tr.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.zh-Hans.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/Program.cs
  test/dotnet.Tests/GivenThatDotNetRunsCommands.cs
Labels: Approved to merge

#9612 Updating the WebSdk from aspnet/websdk/2.1.4xx
  build/DependencyVersions.props
Labels: Approved to merge

#9608 Revert implementation of the --mode option for the publish command.
  build/DependencyVersions.props
  src/dotnet/commands/dotnet-publish/LocalizableStrings.resx
  src/dotnet/commands/dotnet-publish/Program.cs
  src/dotnet/commands/dotnet-publish/PublishCommandParser.cs
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.zh-Hant.xlf
  test/Microsoft.DotNet.Tools.Tests.Utilities/Commands/PublishCommand.cs
  test/dotnet-publish.Tests/GivenDotnetPublishPublishesProjects.cs
Labels: Approved to merge

#9626 Produce/publish the VS.Redist.Common.Net.Core.SDK.MSBuildExtensions artifacts
  build/AzureInfo.props
  build/Package.targets
  build/Publish.targets
  build/package/MSBuildExtensions.targets
  packaging/windows/msbuildextensions/VS.Redist.Common.Net.Core.SDK.MSBuildExtensions.nuspec
  packaging/windows/msbuildextensions/generatenupkg.ps1
Labels: Area-Infrastructure

#9647 Revert version change for ASP.NET bundled templates.
  build/BundledTemplates.props
  build/DependencyVersions.props
Labels: Approved to merge, Area-Infrastructure

#9630 Insert NuGet Build 4.8.0-preview5.5328 into cli
  build/DependencyVersions.props
Labels: Pending M2 Approval

#9355 Add tests for Code coverage with dotnet test
  TestAssets/TestProjects/VSTestCore/VSTestCore.csproj
  TestAssets/TestProjects/VSTestMulti/VSTestDesktopAndNetCore.csproj
  TestAssets/TestProjects/XunitCore/XunitCore.csproj
  TestAssets/TestProjects/XunitMulti/VSTestXunitDesktopAndNetCore.csproj
  build/DependencyVersions.props
  build/NugetConfigFile.targets
  test/dotnet-test.Tests/CollectCodeCoverage.runsettings
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestFromCsprojForMultipleTFM.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
  test/dotnet-test.Tests/dotnet-test.Tests.csproj
Labels: Approved to merge, Area-Infrastructure

#9679 Updating the version of Newtonsoft.Json: 10.0.3
  src/dotnet/dotnet.csproj
Labels: infrastructure

#9684 Pin stage0 used for update-dependencies to stable 2.1 build
  build_projects/update-dependencies/update-dependencies.ps1
  build_projects/update-dependencies/update-dependencies.sh
Labels: Area-Infrastructure

#9709 Update the .NET SDK version.
  build/DependencyVersions.props
Labels: Area-Infrastructure

#9755 Create binlogs by default.
  .gitignore
  run-build.ps1
  run-build.sh
Labels: infrastructure

#9757 Avoid GenerateAssemblyInfo for dotnet migrate tests
  test/dotnet-migrate.Tests/GivenThatIWantToMigrateSolutions.cs
Labels: infrastructure

#9761 NuGetSdkResolverPackageVersion should be MicrosoftBuildNuGetSdkResolverPackageVersion
  build/DependencyVersions.props
  src/redist/redist.csproj
Labels: infrastructure

#9766 Fix dotnet sln add for multitargeted C# and VB projects.
  TestAssets/TestProjects/TestAppsWithSlnAndMultitargetedProjects/MultitargetedCS/MultitargetedCS.csproj
  TestAssets/TestProjects/TestAppsWithSlnAndMultitargetedProjects/MultitargetedCS/Program.cs
  TestAssets/TestProjects/TestAppsWithSlnAndMultitargetedProjects/MultitargetedFS/MultitargetedFS.fsproj
  TestAssets/TestProjects/TestAppsWithSlnAndMultitargetedProjects/MultitargetedFS/Program.fs
  TestAssets/TestProjects/TestAppsWithSlnAndMultitargetedProjects/MultitargetedVB/MultitargetedVB.vbproj
  TestAssets/TestProjects/TestAppsWithSlnAndMultitargetedProjects/MultitargetedVB/Program.vb
  TestAssets/TestProjects/TestAppsWithSlnAndMultitargetedProjects/TestAppsWithSlnAndMultitargetedProjects.sln
  build/DependencyVersions.props
  test/dotnet-sln-add.Tests/GivenDotnetSlnAdd.cs
Labels: Approved to merge

#9582 Add packaged shim doc
  Documentation/general/signing-global-tool-packages.md
Labels: documentation

#9589 tool-nuget-package-format document
  Documentation/general/tool-nuget-package-format.md
Labels: documentation
