Repository dotnet/cli, pull requests merged in 2018-10, with the labels that each got.

#10080 Updating CLI branding to 2.1.404
  build/Version.props
Labels: infrastructure

#10072 Typos/spelling errors in XML doc comments and markdown. #Hacktoberfest
  Documentation/specs/cli-installation-scenarios.md
  Documentation/specs/corehost.md
  src/Microsoft.DotNet.InternalAbstractions/DirectoryPath.cs
  src/Microsoft.DotNet.InternalAbstractions/FilePath.cs
  test/Microsoft.DotNet.Tools.Tests.Utilities/Mock/FileSystemMockBuilder.cs
Labels: community

#9981 Installer metadata in ARP uses HTTP URLs release/2.1.4xx
  packaging/windows/clisdk/bundle.wxs
Labels: Servicing-approved

#10073 Add retry to download
  build_projects/dotnet-cli-build/DownloadFile.cs
  build_projects/dotnet-cli-build/ExponentialRetry.cs
  build_projects/dotnet-cli-build/RetryFailedException.cs
Labels: infrastructure

#10090 Simplify opensuse docker image
  scripts/docker/opensuse.42.3/Dockerfile
Labels: infrastructure

#10099 Add the Razor SDK to the versions to update
  build_projects/update-dependencies/Program.cs
Labels: infrastructure

#10147 Update LatestPatchVersionForNetCore 1.0 and 1.1
  build/MSBuildExtensions.targets
Labels: Approved to merge

#9980 Installer metadata in ARP uses HTTP URLs rel/1.1.0
  packaging/windows/clisdk/bundle.wxs
Labels: Servicing-approved

#10120 Change package id compare from CurrentCultureIgnoreCase to OrdinalIgnoreCase
  src/dotnet/ToolPackage/ToolPackageInstance.cs
  test/Microsoft.DotNet.ToolPackage.Tests/Microsoft.DotNet.ToolPackage.Tests.csproj
  test/Microsoft.DotNet.ToolPackage.Tests/SampleGlobalToolWithDifferentCasing/ConsoleDemoWithCasing.csproj
  test/Microsoft.DotNet.ToolPackage.Tests/SampleGlobalToolWithDifferentCasing/DotnetToolSettings.xml
  test/Microsoft.DotNet.ToolPackage.Tests/SampleGlobalToolWithDifferentCasing/Program.cs
  test/Microsoft.DotNet.ToolPackage.Tests/SampleGlobalToolWithDifferentCasing/includepublish.nuspec
  test/Microsoft.DotNet.ToolPackage.Tests/ToolPackageInstallerTests.cs
Labels: Servicing-consider

#10172 Adding new VS.Redist packages for 2.1, so that we can serve both 15.x and 16.x
  build/package/Installer.MSI.targets
  packaging/windows/clisdk/VS.Redist.Common.Net.Core.SDK.x64.2.1.nuspec
  packaging/windows/clisdk/VS.Redist.Common.Net.Core.SDK.x86.2.1.nuspec
Labels: Area-Infrastructure

#10160 Add local tools command resolver
  src/Microsoft.DotNet.Cli.Utils/Constants.cs
  src/Microsoft.DotNet.Cli.Utils/NuGetGlobalPackagesFolder.cs
  src/Microsoft.DotNet.InternalAbstractions/Properties/Properties.cs
  src/dotnet/CommandFactory/CommandResolution/DefaultCommandResolverPolicy.cs
  src/dotnet/CommandFactory/CommandResolution/DotnetToolsCommandResolver.cs
  src/dotnet/CommandFactory/CommandResolution/LocalToolsCommandResolver.cs
  src/dotnet/CommandFactory/CommandResolution/MuxerCommandSpecMaker.cs
  src/dotnet/CommandFactory/LocalizableStrings.resx
  src/dotnet/CommandFactory/xlf/LocalizableStrings.cs.xlf
  src/dotnet/CommandFactory/xlf/LocalizableStrings.de.xlf
  src/dotnet/CommandFactory/xlf/LocalizableStrings.es.xlf
  src/dotnet/CommandFactory/xlf/LocalizableStrings.fr.xlf
  src/dotnet/CommandFactory/xlf/LocalizableStrings.it.xlf
  src/dotnet/CommandFactory/xlf/LocalizableStrings.ja.xlf
  src/dotnet/CommandFactory/xlf/LocalizableStrings.ko.xlf
  src/dotnet/CommandFactory/xlf/LocalizableStrings.pl.xlf
  src/dotnet/CommandFactory/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/CommandFactory/xlf/LocalizableStrings.ru.xlf
  src/dotnet/CommandFactory/xlf/LocalizableStrings.tr.xlf
  src/dotnet/CommandFactory/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/CommandFactory/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/ToolManifest/ToolManifestFinder.cs
  src/dotnet/ToolManifest/ToolManifestPackage.cs
  src/dotnet/ToolPackage/LocalToolsResolverCache.cs
  src/dotnet/commands/dotnet-tool/install/ProjectRestorer.cs
  src/dotnet/commands/dotnet-tool/restore/ToolRestoreCommand.cs
  test/Microsoft.DotNet.CommandFactory.Tests/GivenADefaultCommandResolver.cs
  test/Microsoft.DotNet.CommandFactory.Tests/GivenALocalToolsCommandResolver.cs
  test/Microsoft.DotNet.CommandFactory.Tests/Microsoft.DotNet.CommandFactory.Tests.csproj
  test/Microsoft.DotNet.ToolPackage.Tests/LocalToolsResolverCacheTests.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ProjectRestorerMock.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/Properties/Properties.cs
  test/Microsoft.DotNet.Tools.Tests.Utilities/Properties/Properties.cs
  test/dotnet.Tests/CommandTests/ToolManifestTests.cs
  test/dotnet.Tests/CommandTests/ToolRestoreCommandTests.cs
Labels: tool
