Repository dotnet/cli, pull requests merged in 2018-02, with the labels that each got.

#8416 Adds Microsoft.Docker.Sdk to CLI
  TestAssets/TestProjects/docker-compose/docker-compose.dcproj
  TestAssets/TestProjects/docker-compose/docker-compose.yml
  build/BundledSdks.props
  build/NugetConfigFile.targets
  test/dotnet-build.Tests/GivenDotnetBuildBuildsDcproj.cs
Labels: approved to merge

#8587 Do not create a directory with a trailing space
  test/Microsoft.DotNet.ShellShim.Tests/ShellShimMakerTests.cs
Labels: infrastructure

#8588 Port Kernel Version telemetry to preview1
  src/dotnet/Telemetry/TelemetryCommonProperties.cs
  test/dotnet.Tests/TelemetryCommonPropertiesTests.cs
Labels: approved to merge

#8580 Insert NuGet Build 4.6.0-rtm-4918 into cli
  build/DependencyVersions.props
Labels: approved to merge

#8589 Support TildeSlash expand
  src/Microsoft.DotNet.Cli.Utils/EnvironmentProvider.cs
Labels: approved to merge

#8595 Update to roslyn 2.7.0-beta3-62612-07 for 2.1.1xx
  build/DependencyVersions.props
  build/Microsoft.DotNet.Cli.tasks
  build_projects/dotnet-cli-build/AddToDeps.cs
  src/redist/redist.csproj
  src/tool_roslyn_satellites/tool_roslyn_satellites.csproj
Labels: approved to merge

#8602 "ExternalRestoreSources" needs to be set in the docker container
  scripts/dockerrun.sh
Labels: build, infrastructure

#8594 Update fsharp
  build/DependencyVersions.props
Labels: approved to merge

#8647 Tag non-shipping nupkg as 'NonShipping=true' in the manifest.
  build/publish/PublishNupkgToBlobFeed.targets
Labels: build
