Repository dotnet/cli, pull requests merged in 2018-09, with the labels that each got.

#9952 Minor change
  src/dotnet/ToolPackage/IToolPackageUninstaller.cs
  src/dotnet/ToolPackage/PackageLocation.cs
  src/dotnet/ToolPackage/ToolPackageInstaller.cs
  src/dotnet/ToolPackage/ToolPackageInstance.cs
  src/dotnet/ToolPackage/ToolPackageStoreAndQuery.cs
  src/dotnet/ToolPackage/ToolPackageUninstaller.cs
Labels: tool

#9956 Update dependency updater (port from 2.2.1xx)
  build_projects/update-dependencies/Program.cs
Labels: Area-Infrastructure

#9960 Update SLA to clarify business days.
  README.md
Labels: Area-Infrastructure

#9892 Expand relative paths for CLI arguments
  src/dotnet/CommandDirectoryContext.cs
  src/dotnet/commands/dotnet-build/BuildCommandParser.cs
  src/dotnet/commands/dotnet-clean/CleanCommandParser.cs
  src/dotnet/commands/dotnet-pack/PackCommandParser.cs
  src/dotnet/commands/dotnet-publish/PublishCommandParser.cs
  src/dotnet/commands/dotnet-restore/RestoreCommandParser.cs
  src/dotnet/commands/dotnet-store/StoreCommandParser.cs
  src/dotnet/commands/dotnet-test/TestCommandParser.cs
  test/Microsoft.DotNet.Tools.Tests.Utilities/TestPathUtilities.cs
  test/dotnet-msbuild.Tests/GivenDotnetBuildInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetCleanInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetPackInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetPublishInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetRestoreInvocation.cs
  test/dotnet-msbuild.Tests/GivenDotnetStoreInvocation.cs
Labels: breaking-change, community

#9953 Add local tool resolver cache
  src/dotnet/ToolPackage/IToolPackage.cs
  src/dotnet/ToolPackage/LocalToolsResolverCache.cs
  src/dotnet/ToolPackage/ResolverCacheInconsistentException.cs
  src/dotnet/ToolPackage/RestoredCommand.cs
  src/dotnet/ToolPackage/RestoredCommandIdentifier.cs
  src/dotnet/ToolPackage/RestoredCommandIdentifierVersionRange.cs
  src/dotnet/ToolPackage/ToolPackageInstance.cs
  src/dotnet/commands/dotnet-tool/update/ToolUpdateCommand.cs
  test/Microsoft.DotNet.ToolPackage.Tests/LocalToolsResolverCacheTests.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageInstallerMock.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageMock.cs
  test/dotnet.Tests/CommandTests/ToolListCommandTests.cs
Labels: tool

#9983 Update dependencies for the 2.1.402 release.
  build/DependencyVersions.props
Labels: Area-Infrastructure

#9986 Update core-setup and re-enable all sdk resolver tests
  build/DependencyVersions.props
  src/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  test/Microsoft.DotNet.MSBuildSdkResolver.Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests.csproj
Labels: Approved to merge

#9998 NonSuffix ProdCon CLI builds should drop to a NonSuffix folder
  build/Publish.targets
  build/Version.props
Labels: infrastructure

#10021 Always use the suffixed version for the 'VS' NuPkgs
  build/Publish.targets
  build/Version.props
  build/package/Installer.MSI.targets
Labels: infrastructure

#10018 Add ImplicitPackageReferenceVersion items to bundled versions file
  build/DependencyVersions.props
  build/MSBuildExtensions.targets
Labels: Servicing-approved

#10023 Improve runtime configuration documentation
  Documentation/specs/runtime-configuration-file.md
Labels: documentation

#10039 Avoid setting dotnet tool path permanently during test
  test/Microsoft.DotNet.Tools.Tests.Utilities/Commands/TestCommand.cs
Labels: infrastructure, tool

#9868 Adding NuGet project lock file options for dotnet restore command
  src/dotnet/commands/dotnet-restore/LocalizableStrings.resx
  src/dotnet/commands/dotnet-restore/RestoreCommandParser.cs
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-restore/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-msbuild.Tests/GivenDotnetRestoreInvocation.cs
Labels: Approved to merge

#10036 Remove Get-CimInstance dependency from dotnet-install.ps1
  scripts/obtain/dotnet-install.ps1
Labels: Install-Script
