Repository dotnet/cli, pull requests merged in 2018-05, with the labels that each got.

#9180 Simplify completions scripts
  scripts/register-completions.bash
  scripts/register-completions.zsh
Labels: community

#9177 Remove mac mark all 755
  packaging/osx/clisdk/scripts/postinstall
Labels: Approved to merge

#9171 Use NuGet autocomplete API for add-package suggestions
  src/dotnet/commands/dotnet-add/dotnet-add-package/AddPackageParser.cs
Labels: community

#9178 Add a property to disable bundling ASP.NET Core tools and runtimes
  build/BundledDotnetTools.props
  build/BundledRuntimes.props
  build/MSBuildExtensions.targets
  src/Microsoft.DotNet.Configurer/DotnetFirstTimeUseConfigurer.cs
  src/Microsoft.DotNet.Configurer/Microsoft.DotNet.Configurer.csproj
  src/dotnet/AspNetCoreCertificateGenerator.cs
  src/dotnet/dotnet.csproj
Labels: Approved to merge

#9188 Removing some patches for source build.
  build/GitCommitInfo.targets
  build/NugetConfigFile.targets
  run-build.sh
  src/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/redist/redist.csproj
Labels: Approved to merge

#9187 Allow ExternalRestoreSources in offline build (remove source-build patch 0003)
  build/NugetConfigFile.targets
Labels: Approved to merge

#9199 Removing the word please from the ASP.NET first run message.
  src/Microsoft.DotNet.Configurer/LocalizableStrings.resx
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.cs.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.de.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.es.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.fr.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.it.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.ja.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.ko.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.pl.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.pt-BR.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.ru.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.tr.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.zh-Hans.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Approved to merge

#9202 Fixing CI build breaks for new CI legs; CLI:release/2.1.3xx
  build/BuildDefaults.props
  test/EndToEnd/GivenSelfContainedAppsRollForward.cs
Labels: Approved to merge, infrastructure

#9214 Fix adding tools directory to PATH for native installers.
  src/Microsoft.DotNet.Configurer/NoOpFileSentinel.cs
  src/dotnet/Program.cs
  test/dotnet.Tests/GivenThatTheUserIsRunningDotNetForTheFirstTime.cs
Labels: Approved to merge

#9213 Making the CLI package name be only major.minor version and updating the version of the runtime packages that we depend on.
  build/BundledRuntimes.props
  build/DependencyVersions.props
  build/Package.targets
  build/Version.props
  build/package/Installer.DEB.targets
  build/package/Installer.RPM.targets
  build/package/LinuxNativeInstallerDependencyVersions.targets
  packaging/deb/dotnet-debian_config.json
Labels: Approved to merge

#9254 Use the latest nuget.exe in generatenupkg script
  packaging/windows/clisdk/generatenupkg.ps1
Labels: community, infrastructure

#9261 MSBuild 15.7.179 (2xx)
  build/DependencyVersions.props
Labels: Approved to merge

#9264 Updating the CLI branding to 201.
  build/Branding.props
  build/Version.props
  packaging/osx/clisdk/resources/cs.lproj/conclusion.html
  packaging/osx/clisdk/resources/de.lproj/conclusion.html
  packaging/osx/clisdk/resources/en.lproj/conclusion.html
  packaging/osx/clisdk/resources/es.lproj/conclusion.html
  packaging/osx/clisdk/resources/fr.lproj/conclusion.html
  packaging/osx/clisdk/resources/it.lproj/conclusion.html
  packaging/osx/clisdk/resources/ja.lproj/conclusion.html
  packaging/osx/clisdk/resources/ko.lproj/conclusion.html
  packaging/osx/clisdk/resources/pl.lproj/conclusion.html
  packaging/osx/clisdk/resources/pt-br.lproj/conclusion.html
  packaging/osx/clisdk/resources/ru.lproj/conclusion.html
  packaging/osx/clisdk/resources/tr.lproj/conclusion.html
  packaging/osx/clisdk/resources/zh-hans.lproj/conclusion.html
  packaging/osx/clisdk/resources/zh-hant.lproj/conclusion.html
  packaging/windows/clisdk/bundle.wxl
Labels: Approved to merge

#9267 Fix incorrect default VSTest verbosity level.
  src/dotnet/ArgumentForwardingExtensions.cs
  src/dotnet/commands/dotnet-test/Program.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
Labels: Approved to merge, Blocking-RTM

#9262 MSBuild 15.7.179
  build/DependencyVersions.props
  build/NugetConfigFile.targets
Labels: Approved to merge

#9278 Accept DropSuffix as a boolean
  build/MSBuildExtensions.targets
  build/Version.props
Labels: Approved to merge

#9297 Add NoWarn=NU5104 when packaging Cli.Utils for tests.
  build/test/TestPackageProjects.targets
  src/redist/redist.csproj
  src/tool_fsharp/tool_fsc.csproj
Labels: Approved to merge

#9300 Add the NoWarn option when producing Cli.Utils for full framework as well
  build/test/TestPackageProjects.targets
Labels: Approved to merge

#9302 Multiple Logger/TestAdapter inputs from dotnet CLI
  src/dotnet/commands/dotnet-test/TestCommandParser.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
Labels: Approved to merge, community

#9292 Fix header output by `dotnet sln list`.
  src/dotnet/commands/dotnet-sln/LocalizableStrings.resx
  src/dotnet/commands/dotnet-sln/list/Program.cs
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-sln-list.Tests/GivenDotnetSlnList.cs
Labels: Approved to merge

#9294 Improve command completion.
  src/dotnet/Parser.cs
  src/dotnet/commands/dotnet-complete/CompleteCommand.cs
  src/dotnet/commands/dotnet-internal-reportinstallsuccess/InternalReportinstallsuccessCommandParser.cs
  src/dotnet/commands/dotnet-new/NewCommandParser.cs
  src/dotnet/commands/dotnet-new/NewCommandShim.cs
  src/dotnet/commands/dotnet-nuget/NuGetCommandParser.cs
  test/dotnet.Tests/CommandTests/CompleteCommandTests.cs
  test/dotnet.Tests/TelemetryCommandTest.cs
Labels: Approved to merge

#9259 Insert NuGet Build 4.8.0-preview1.5196 into cli
  build/DependencyVersions.props
  test/binding-redirects.Tests/binding-redirects.Tests.csproj
Labels: Approved to merge

#9307 Updating netci.groovy to archive test results on failure.
  netci.groovy
Labels: Approved to merge

#9324 Validate the SDK installation
  scripts/obtain/dotnet-install.ps1
  scripts/obtain/dotnet-install.sh
Labels: Install-Script

#9279 MSBuild 15.8.61
  build/DependencyVersions.props
  src/redist/redist.csproj
  test/Microsoft.DotNet.MSBuildSdkResolver.Tests/GivenAnMSBuildSdkResolver.cs
Labels: Approved to merge

#9313 Add retry when Directory.Move
  src/Microsoft.DotNet.Cli.Utils/FileAccessRetryer.cs
  src/dotnet/ShellShim/ShellShimRepository.cs
  src/dotnet/ToolPackage/ToolPackageInstaller.cs
  src/dotnet/ToolPackage/ToolPackageInstance.cs
Labels: Approved to merge

#9329 Don't add the ReleaseSuffix to the branding on the CLI
  build/Version.props
Labels: Pending shiproom approval

#9265 Always execute cache expansion on native installers.
  src/Microsoft.DotNet.Configurer/DotnetFirstRunConfiguration.cs
  src/Microsoft.DotNet.Configurer/DotnetFirstTimeUseConfigurer.cs
  src/dotnet/Program.cs
  test/Microsoft.DotNet.Configurer.UnitTests/GivenADotnetFirstTimeUseConfigurer.cs
  test/Microsoft.DotNet.TestFramework/Microsoft.DotNet.TestFramework.csproj
Labels: Approved to merge

#9338 Fixing the netci.groovy, CLI:rel/1.1.0
  netci.groovy
Labels: infrastructure

#9327 Fix crash when user home directory cannot be determined.
  src/Microsoft.DotNet.Cli.Utils/Properties/AssemblyInfo.cs
  src/Microsoft.DotNet.Configurer/AspNetCertificateSentinel.cs
  src/Microsoft.DotNet.Configurer/CliFolderPathCalculator.cs
  src/Microsoft.DotNet.Configurer/ConfigurationException.cs
  src/Microsoft.DotNet.Configurer/FirstTimeUseNoticeSentinel.cs
  src/Microsoft.DotNet.Configurer/LocalizableStrings.resx
  src/Microsoft.DotNet.Configurer/Microsoft.DotNet.Configurer.csproj
  src/Microsoft.DotNet.Configurer/NuGetCachePrimer.cs
  src/Microsoft.DotNet.Configurer/NuGetCacheSentinel.cs
  src/Microsoft.DotNet.Configurer/UserLevelCacheWriter.cs
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.cs.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.de.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.es.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.fr.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.it.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.ja.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.ko.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.pl.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.pt-BR.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.ru.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.tr.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.zh-Hans.xlf
  src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/Program.cs
  src/dotnet/ShellShim/EnvironmentPathFactory.cs
  src/dotnet/ShellShim/ShellShimRepositoryFactory.cs
  src/dotnet/Telemetry/TelemetryCommonProperties.cs
  src/dotnet/ToolPackage/ToolPackageFactory.cs
  src/dotnet/ToolPackage/ToolPackageInstaller.cs
  src/dotnet/commands/dotnet-msbuild/MSBuildLogger.cs
  src/dotnet/commands/dotnet-new/NewCommandShim.cs
  src/dotnet/commands/dotnet-tool/install/ToolInstallCommand.cs
  src/dotnet/commands/dotnet-tool/uninstall/ToolUninstallCommand.cs
  test/Microsoft.DotNet.Configurer.UnitTests/GivenANuGetCachePrimer.cs
  test/Microsoft.DotNet.Configurer.UnitTests/GivenAPathCalculator.cs
  test/dotnet.Tests/GivenThatDotNetRunsCommands.cs
  test/dotnet.Tests/GivenThatIWantToManageMulticoreJIT.cs
  test/dotnet.Tests/GivenThatTheUserIsRunningDotNetForTheFirstTime.cs
Labels: Approved to merge

#9333 Fixing the 'signing' step.
  build/Microsoft.DotNet.Cli.DependencyVersions.props
  build/Microsoft.DotNet.Cli.Signing.proj
  tools/SigningDependencies/SigningDependencies.csproj
Labels: build

#9330 Fix relative path tool path
  src/Microsoft.DotNet.Cli.Utils/PathUtility.cs
  src/dotnet/ShellShim/AppHostShimMaker.cs
  test/Microsoft.DotNet.ShellShim.Tests/ShellShimRepositoryTests.cs
Labels: Approved to merge

#9345 Stabilizing on a 1.1.9-servicing-005253 SDK 'build-engine'
  run-build.ps1
  run-build.sh
Labels: build

#9348 Update dependencies and branding
  build/DependencyVersions.props
  build/Version.props
Labels: Approved to merge

#9373 MSBuild 15.8.78
  build/DependencyVersions.props
Labels: Approved to merge

#9354 Change configuration completion suggestion to standard capitalization
  src/dotnet/CommonOptions.cs
Labels: Approved to merge, community
