Repository dotnet/cli, pull requests merged in 2018-08, with the labels that each got.

#9829 Add back: PUBLISH_NUPKG_TO_BLOB_FEED
  build/publish/PublishNupkgToBlobFeed.targets
Labels: Area-Infrastructure

#9846 Fix warnings
  build/BuildDefaults.props
  build/package/Installer.DEB.proj
  scripts/docker/debian/Dockerfile
Labels: infrastructure

#9847 Fix test with framework-dependent apphost.
  build/DependencyVersions.props
  test/dotnet-publish.Tests/GivenDotnetPublishPublishesProjects.cs
Labels: Area-Infrastructure

#9848 Update error text; adding a link to some helpful documentation.
  scripts/obtain/dotnet-install.ps1
  scripts/obtain/dotnet-install.sh
Labels: Install-Script

#9880 Fix test break
  test/dotnet-new.Tests/GivenThatIWantANewAppWithSpecifiedType.cs
Labels: Area-Infrastructure

#9882 Updating the windows installer notice to reflect 2.2 and its requirem…
  packaging/windows/clisdk/bundle.wxl
Labels: servicing-approved

#9902 Changing the property names for 2.2 templates to be named 22 instead of 20.
  build/BundledTemplates.props
  build/DependencyVersions.props
Labels: Area-Infrastructure

#9906 Fix rpmdb error
  build/package/Installer.RPM.targets
  scripts/docker/rhel/Dockerfile
Labels: infrastructure

#9914 Fix debian package tests clean up and set up
  build/package/Installer.DEB.proj
Labels: infrastructure

#9930 Update BuildTasksFeedToolVersion
  build/DependencyVersions.props
  build_projects/dotnet-cli-build/dotnet-cli-build.csproj
Labels: Area-Infrastructure
