Repository dotnet/cli, pull requests merged in 2019-08, with the labels that each got.

#12166 Fixing broken link to developer guide
  Documentation/general/intro-to-cli.md
Labels: infrastructure

#12149 Solution items are now considered when removing empty folders
  TestAssets/TestProjects/SlnFileWithSolutionItemsInNestedFolders/App.sln
  src/dotnet/SlnFileExtensions.cs
  test/dotnet-sln-remove.Tests/GivenDotnetSlnRemove.cs
Labels: community

#12176 Add yaml stages
  .vsts-ci.yml
  eng/build.yml
Labels: tell-mode

#12301 Remove link to non-existing document
  Documentation/README.md
Labels: documentation

#12315 Add support for Microsoft.WindowsDesktop.App
  scripts/obtain/dotnet-install.ps1
  scripts/obtain/dotnet-install.sh
Labels: Install-Script
