Repository dotnet/cli, pull requests merged in 2019-04, with the labels that each got.

#10914 Change message when the executable cannot be found to File not found {0} for issue #10911
  src/Microsoft.DotNet.Cli.Utils/LocalizableStrings.resx
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.cs.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.de.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.es.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.fr.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.it.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.ja.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.ko.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.pl.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.pt-BR.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.ru.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.tr.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.zh-Hans.xlf
  src/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.zh-Hant.xlf
Labels: community

#11045 Fix bash completion when the SDK is not installed
  scripts/register-completions.bash
Labels: community

#11070 Make sure that an empty argument is preserved.
  src/Microsoft.DotNet.Cli.Utils/ArgumentEscaper.cs
  test/dotnet-run.Tests/GivenDotnetRunRunsCsProj.cs
Labels: community

#11000 Add solution folder argument to dotnet-sln add
  src/dotnet/SlnFileExtensions.cs
  src/dotnet/SlnProjectExtensions.cs
  src/dotnet/commands/dotnet-sln/LocalizableStrings.resx
  src/dotnet/commands/dotnet-sln/add/Program.cs
  src/dotnet/commands/dotnet-sln/add/SlnAddParser.cs
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-sln-add.Tests/GivenDotnetSlnAdd.cs
Labels: community

#11138 Insert NuGet Build 5.0.1-rtm.5946 into cli
  build/DependencyVersions.props
Labels: Servicing-approved

#11137 Insert NuGet Build 5.0.1-rtm.5946 into cli
  build/DependencyVersions.props
Labels: Servicing-approved

#11179 dotnet tool uninstall should find the first manifest file contain package id
  src/dotnet/commands/dotnet-tool/common/LocalizableStrings.resx
  src/dotnet/commands/dotnet-tool/common/ToolManifestFinderExtensions.cs
  src/dotnet/commands/dotnet-tool/common/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-tool/common/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-tool/common/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-tool/common/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-tool/common/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-tool/common/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-tool/common/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-tool/common/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-tool/common/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-tool/common/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-tool/common/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-tool/common/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-tool/common/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/commands/dotnet-tool/uninstall/LocalizableStrings.resx
  src/dotnet/commands/dotnet-tool/uninstall/ToolUninstallLocalCommand.cs
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/commands/dotnet-tool/update/LocalizableStrings.resx
  src/dotnet/commands/dotnet-tool/update/ToolUpdateLocalCommand.cs
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet.Tests/CommandTests/ToolUninstallCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolUninstallLocalCommandTests.cs
Labels: tool

#11239 release/2.1.7xx: Update debain jessie image
  scripts/docker/debian/Dockerfile
Labels: infrastructure

#11238 release/2.2.3xx: Update debain jessie image
  scripts/docker/debian/Dockerfile
Labels: infrastructure

#11244 Update the BranchInfo for release/2.2.3xx
  build/BranchInfo.props
Labels: infrastructure

#11245 Update the BranchInfo for release/2.1.7xx
  build/BranchInfo.props
Labels: infrastructure

#11246 Rebuild release/2.1.6xx
  README.md
Labels: Area-Infrastructure

#11247 Rebuild release/2.2.2xx
  README.md
Labels: Area-Infrastructure

#11260 Update the SDK to `2.1.700-preview-64023-01`.
  build/DependencyVersions.props
Labels: Area-Infrastructure

#11261 Update SDK version to `2.2.300-preview-64023-02`.
  build/DependencyVersions.props
Labels: Area-Infrastructure
