Repository dotnet/cli, pull requests merged in 2019-10, with the labels that each got.

#12750 Enable SDK version harvesting from a global.json file
  TestAssets/InstallationScriptTests/InstallationScriptTests.json
  scripts/obtain/dotnet-install.ps1
  scripts/obtain/dotnet-install.sh
  test/InstallationScript.Tests/GivenThatIWantToInstallTheSdkFromAScript.cs
Labels: Install-Script

#12899 Fix eventProperties.Add mutate _commonProperties
  src/dotnet/Telemetry/Telemetry.cs
Labels: ask-mode

#12972 Fix typo
  Directory.Build.targets
Labels: tell-mode

#13003 Remove signature on MAC host for dotnet tools
  src/Microsoft.DotNet.Cli.Utils/AppHostMachOFormatException.cs
  src/Microsoft.DotNet.Cli.Utils/EmbedAppNameInHost.cs
  src/Microsoft.DotNet.Cli.Utils/MachOUtils.cs
  src/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
Labels: Servicing-approved
