Repository dotnet/cli, pull requests merged in 2019-02, with the labels that each got.

#10712 Localize MSBuild SDK resolver
  src/Microsoft.DotNet.MSBuildSdkResolver/MSBuildSdkResolver.cs
  src/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Microsoft.DotNet.MSBuildSdkResolver/Strings.resx
  src/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.cs.xlf
  src/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.de.xlf
  src/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.es.xlf
  src/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.fr.xlf
  src/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.it.xlf
  src/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.ja.xlf
  src/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.ko.xlf
  src/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.pl.xlf
  src/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.pt-BR.xlf
  src/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.ru.xlf
  src/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.tr.xlf
  src/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.zh-Hans.xlf
  src/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.zh-Hant.xlf
  test/Microsoft.DotNet.MSBuildSdkResolver.Tests/GivenAnMSBuildSdkResolver.cs
Labels: Servicing-approved

#10716 Updating 2.2 test templates
  build/DependencyVersions.props
Labels: Servicing-approved

#10733 Fix typo: s/Interective/Interactive/
  src/dotnet/commands/dotnet-help/LocalizableStrings.resx
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
Labels: Servicing-approved

#10822 Adding resolver satellite assemblies to be signed.
  build/Signing.proj
Labels: Area-Infrastructure

#10791 Add --version to dotnet tool update -g
  src/dotnet/commands/dotnet-tool/update/LocalizableStrings.resx
  src/dotnet/commands/dotnet-tool/update/ToolUpdateCommand.cs
  src/dotnet/commands/dotnet-tool/update/ToolUpdateCommandParser.cs
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet.Tests/CommandTests/ToolUpdateCommandTests.cs
  test/dotnet.Tests/ParserTests/UpdateToolParserTests.cs
Labels: tool

#10831 Sign resolver satellites in layout
  build/Signing.proj
Labels: Area-Infrastructure

#10867 Add properties to control shared framework versions for servicing releases.
  build/MSBuildExtensions.targets
  test/EndToEnd/GivenSelfContainedAppsRollForward.cs
Labels: Approved to merge, Area-Infrastructure

#10884 Skip the self-contained roll-forward version tests.
  test/EndToEnd/GivenSelfContainedAppsRollForward.cs
Labels: Approved to merge, Area-Infrastructure

#10888 Parameterize latest patch versions.
  build/MSBuildExtensions.targets
Labels: Approved to merge, Area-Infrastructure

#10828 Update command description
  src/dotnet/commands/dotnet-build/BuildCommandParser.cs
  src/dotnet/commands/dotnet-clean/CleanCommandParser.cs
  src/dotnet/commands/dotnet-publish/PublishCommandParser.cs
  src/dotnet/commands/dotnet-restore/RestoreCommandParser.cs
  src/dotnet/commands/dotnet-test/TestCommandParser.cs
Labels: community
