Repository dotnet/cli, pull requests merged in 2019-07, with the labels that each got.

#11855 Update 1.x and 2.1 servicing versions.
  build/MSBuildExtensions.targets
  build/Version.props
Labels: Pending director approval

#11854 Update 1.x servicing versions to the latest versions.
  build/MSBuildExtensions.targets
  build/Version.props
Labels: Pending director approval

#11916 Fixed build failing for usernames with spaces
  run-build.ps1
Labels: community

#11903 Update 1.x servicing versions to the latest versions.
  build/MSBuildExtensions.targets
Labels: infrastructure

#11904 Update 1.x and 2.1 servicing versions.
  build/MSBuildExtensions.targets
Labels: infrastructure

#11926 Give specific instruction for zsh on macOS for global tools PATH
  eng/common/dotnet-install.sh
  src/dotnet/CommonLocalizableStrings.resx
  src/dotnet/ShellShim/EnvironmentPathFactory.cs
  src/dotnet/ShellShim/OsxBashEnvironmentPath.cs
  src/dotnet/ShellShim/OsxZshEnvironmentPathInstruction.cs
  src/dotnet/ShellShim/ZshDetector.cs
  src/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
  test/Microsoft.DotNet.ShellShim.Tests/EnvironmentPathFactoryTests.cs
  test/Microsoft.DotNet.ShellShim.Tests/OsxEnvironmentPathTests.cs
  test/Microsoft.DotNet.ShellShim.Tests/OsxZshEnvironmentPathInstructionTests.cs
  test/Microsoft.DotNet.ShellShim.Tests/ZshDetectorTests.cs
Labels: tool

#11629 Don't let dotnet-install.sh fail with 'Text file busy'
  scripts/obtain/dotnet-install.sh
Labels: Pending discussion

#11955 Copy PE bits to shims during install
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.DotNet.Cli.Utils/EmbedAppNameInHost.cs
  src/Microsoft.DotNet.Cli.Utils/EmbedAppNameInHostException.cs
  src/dotnet/ShellShim/AppHostShimMaker.cs
  src/dotnet/dotnet.csproj
  test/Microsoft.DotNet.ShellShim.Tests/AppHostShellShimMakerTests.cs
  test/Microsoft.DotNet.ShellShim.Tests/Microsoft.DotNet.ShellShim.Tests.csproj
  test/Microsoft.DotNet.ShellShim.Tests/ShellShimRepositoryTests.cs
  test/Microsoft.DotNet.ShellShim.Tests/WpfBinaryTestAsssets/testwpf.dll
Labels: tool

#12001 Fix for RHEL 6 workstation
  scripts/obtain/dotnet-install.sh
Labels: Install-Script
