Repository dotnet/cli, pull requests merged in 2019-03, with the labels that each got.

#10913 Clean up
  Documentation/specs/corehost.md
Labels: community

#10922 Prevent stage0 bundled versions from interfering with the build.
  build/MSBuildExtensions.targets
Labels: Area-Infrastructure

#10789 Closes dotnet list reference help text and output #10428
  src/dotnet/AppliedOptionExtensions.cs
  src/dotnet/CommandBase.cs
  src/dotnet/CommonLocalizableStrings.resx
  src/dotnet/DotNetTopLevelCommandBase.cs
  src/dotnet/ParseResultExtensions.cs
  src/dotnet/commands/dotnet-list/ListCommandParser.cs
  src/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.xlf
  src/dotnet/commands/dotnet-list/dotnet-list-reference/ListProjectToProjectReferencesCommand.cs
  src/dotnet/commands/dotnet-list/dotnet-list-reference/LocalizableStrings.resx
  src/dotnet/commands/dotnet-list/dotnet-list-reference/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-list/dotnet-list-reference/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-list/dotnet-list-reference/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-list/dotnet-list-reference/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-list/dotnet-list-reference/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-list/dotnet-list-reference/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-list/dotnet-list-reference/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-list/dotnet-list-reference/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-list/dotnet-list-reference/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-list/dotnet-list-reference/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-list/dotnet-list-reference/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-list/dotnet-list-reference/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-list/dotnet-list-reference/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
Labels: community

#10903 fix UnauthorizedAccessException when opening readonly sln file for read
  src/Microsoft.DotNet.Cli.Sln.Internal/SlnFile.cs
  test/Microsoft.DotNet.Cli.Sln.Internal.Tests/Microsoft.DotNet.Cli.Sln.Internal.Tests.cs
  test/Microsoft.DotNet.Tools.Tests.Utilities/TempFileSystem/TempFile.cs
  test/dotnet-sln-list.Tests/GivenDotnetSlnList.cs
Labels: community

#10894 Nicer message for `dotnet tool install` failure
  src/Microsoft.DotNet.Cli.Utils/GracefulException.cs
  src/dotnet/ToolManifest/LocalizableStrings.resx
  src/dotnet/ToolManifest/ToolManifestCannotBeFoundException.cs
  src/dotnet/ToolManifest/ToolManifestFinder.cs
  src/dotnet/ToolManifest/xlf/LocalizableStrings.cs.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.de.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.es.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.fr.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.it.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.ja.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.ko.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.pl.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.ru.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.tr.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/ToolManifest/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/commands/dotnet-tool/install/LocalizableStrings.resx
  src/dotnet/commands/dotnet-tool/install/ToolInstallLocalCommand.cs
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/commands/dotnet-tool/restore/ToolRestoreCommand.cs
  src/dotnet/commands/dotnet-tool/uninstall/LocalizableStrings.resx
  src/dotnet/commands/dotnet-tool/uninstall/ToolUninstallLocalCommand.cs
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-tool/uninstall/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet.Tests/CommandTests/ToolInstallLocalCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolManifestFinderTests.cs
  test/dotnet.Tests/CommandTests/ToolRestoreCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolUninstallLocalCommandTests.cs
Labels: tool

#10949 Limit job object usage to Windows 8/2012 or later.
  src/Microsoft.DotNet.Cli.Utils/ProcessReaper.cs
Labels: blocking-partner

#10984 Fix typo
  packaging/windows/clisdk/VS.Redist.Common.Net.Core.SDK.x64.2.1.nuspec
  packaging/windows/clisdk/VS.Redist.Common.Net.Core.SDK.x86.2.1.nuspec
  src/dotnet/commands/dotnet-buildserver/xlf/LocalizableStrings.ja.xlf
  src/dotnet/xlf/CommonLocalizableStrings.es.xlf
Labels: community

#10873 add --no-solution-folders flag to dotnet sln add
  Microsoft.DotNet.Cli.sln
  src/dotnet/SlnFileExtensions.cs
  src/dotnet/commands/dotnet-sln/LocalizableStrings.resx
  src/dotnet/commands/dotnet-sln/add/Program.cs
  src/dotnet/commands/dotnet-sln/add/SlnAddParser.cs
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-sln-add.Tests/GivenDotnetSlnAdd.cs
Labels: community

#11032 Update debain jessie image
  scripts/docker/debian/Dockerfile
Labels: Area-Infrastructure, infrastructure

#11033 fix add package when package directory has spaces
  src/dotnet/commands/dotnet-add/dotnet-add-package/Program.cs
  test/dotnet-add-package.Tests/GivenDotnetPackageAdd.cs
Labels: community
