Repository dotnet/cli, pull requests merged in 2019-06, with the labels that each got.

#11461 On a x64 OS, the x86 SDK bundle installer displays the incorrect installation directory
  packaging/windows/clisdk/bundle.wxs
Labels: Area: Setup

#11481 Remove dotnet migrate
  Microsoft.DotNet.Cli.sln
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.DotNet.Cli.Utils/MSBuildProjectExtensions.cs
  src/Microsoft.DotNet.Cli.Utils/Properties/AssemblyInfo.cs
  src/dotnet/BuiltInCommandsCatalog.cs
  src/dotnet/Parser.cs
  src/dotnet/Telemetry/TelemetryFilter.cs
  src/dotnet/commands/dotnet-help/HelpUsageText.cs
  src/dotnet/commands/dotnet-help/LocalizableStrings.resx
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/commands/dotnet-migrate/DotnetNewRedirector.cs
  src/dotnet/commands/dotnet-migrate/DotnetSlnRedirector.cs
  src/dotnet/commands/dotnet-migrate/LocalizableStrings.resx
  src/dotnet/commands/dotnet-migrate/MigrateCommandCompose.cs
  src/dotnet/commands/dotnet-migrate/MigrateCommandParser.cs
  src/dotnet/commands/dotnet-migrate/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-migrate/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-migrate/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-migrate/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-migrate/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-migrate/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-migrate/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-migrate/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-migrate/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-migrate/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-migrate/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-migrate/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-migrate/xlf/LocalizableStrings.zh-Hant.xlf
  src/dotnet/dotnet.csproj
  test/Microsoft.DotNet.Tools.Tests.Utilities/Commands/MigrateCommand.cs
  test/Msbuild.Tests.Utilities/Msbuild.Tests.Utilities.csproj
  test/Msbuild.Tests.Utilities/ProjectRootElementExtensions.cs
  test/dotnet-add-reference.Tests/dotnet-add-reference.Tests.csproj
  test/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
  test/dotnet-list-reference.Tests/dotnet-list-reference.Tests.csproj
  test/dotnet-migrate.Tests/GivenThatIWantToMigrateSolutions.cs
  test/dotnet-migrate.Tests/MSBuild.exe
  test/dotnet-migrate.Tests/MSBuild.exe.config
  test/dotnet-migrate.Tests/dotnet-migrate.Tests.csproj
  test/dotnet-remove-package.Tests/dotnet-remove-package.Tests.csproj
  test/dotnet-remove-reference.Tests/dotnet-remove-reference.Tests.csproj
  test/dotnet.Tests/CommandTests/CompleteCommandTests.cs
  test/dotnet.Tests/GivenThatTheUserRequestsHelp.cs
  test/dotnet.Tests/ParserTests/MigrateParserTests.cs
Labels: breaking-change

#11374 add no-self-contained option for dotnet publish
  src/dotnet/commands/dotnet-publish/LocalizableStrings.resx
  src/dotnet/commands/dotnet-publish/Program.cs
  src/dotnet/commands/dotnet-publish/PublishCommandParser.cs
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.cs.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.de.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.es.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.fr.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.it.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ja.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ko.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.pl.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.pt-BR.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ru.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.tr.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.zh-Hans.xlf
  src/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-publish.Tests/GivenDotnetPublishPublishesProjects.cs
Labels: community

#11493 Remove unused variables from BundledVersions.props.
  build/MSBuildExtensions.targets
Labels: Servicing-approved, infrastructure

#11534 Spelling.
  eng/common/tools.ps1
Labels: community

#11639 Use live code flow for corefx dependency and react to S.T.Json breaks
  Directory.Build.targets
  eng/Version.Details.xml
  eng/Versions.props
  global.json
  src/dotnet/ToolManifest/JsonElementExtension.cs
  src/dotnet/ToolManifest/ToolManifestEditor.cs
  src/dotnet/ToolPackage/LocalToolsResolverCache.cs
  src/dotnet/commands/dotnet-run/LaunchSettings/LaunchSettingsManager.cs
  src/dotnet/commands/dotnet-run/LaunchSettings/ProjectLaunchSettingsProvider.cs
  src/redist/redist.csproj
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/AppHostShellShimMakerMock.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ProjectRestorerMock.cs
  test/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
Labels: source-build
