Repository dotnet/cli, pull requests merged in 2020-07, with the labels that each got.

#13429 Update branding to 2.1.614
  build/Version.props
Labels: Auto-Merge If Tests Pass, auto-merge

#13433 Use Azure Artifacts instead of MyGet
  TestAssets/TestPackages/dotnet-desktop-and-portable/NuGet.Config
  build/NugetConfigFile.targets
  test/Microsoft.DotNet.Tools.Tests.Utilities/NuGetConfig.cs
  test/dotnet.Tests/ParserTests/RestoreParserTests.cs
Labels: Area-Infrastructure, Infrastructure

#13432 Use Azure Artifacts instead of MyGet
  TestAssets/TestPackages/dotnet-desktop-and-portable/NuGet.Config
  build/NugetConfigFile.targets
  test/Microsoft.DotNet.Tools.Tests.Utilities/NuGetConfig.cs
  test/dotnet.Tests/ParserTests/RestoreParserTests.cs
Labels: Area-Infrastructure, Infrastructure

#13431 Use Azure Artifacts instead of MyGet
  TestAssets/TestPackages/dotnet-desktop-and-portable/NuGet.Config
  build/NugetConfigFile.targets
  test/Microsoft.DotNet.Tools.Tests.Utilities/NuGetConfig.cs
  test/dotnet.Tests/ParserTests/RestoreParserTests.cs
Labels: Infrastructure
